<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_it will help us greatly_form-control__loader</name>
   <tag></tag>
   <elementGuidId>363116cc-c5e5-4f29-899d-d8aeae1ab758</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ecwid-products']/div[2]/div/div/div[2]/div/div[2]/div/div/div[2]/div/div[2]/div[4]/div[2]/div[2]/div[6]/div/div/div/button/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-control__loader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Place Order&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>43cbbb62-d12e-4d49-a2f9-0754179175fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__loader</value>
      <webElementGuid>4f482260-19d6-4e37-8636-2fd0e6f462da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ecwid-products&quot;)/div[@class=&quot;ec-storefront-v2 ec-size ec-size--xxs ec-size--xs ec-size--s ec-size--m ecwid-no-touch ecwid-supports-cssanimations ecwid-responsive ecwid-no-dragndrop&quot;]/div[1]/div[@class=&quot;ecwid-productBrowser ecwid-productBrowser-CheckoutPaymentDetailsPage&quot;]/div[2]/div[@class=&quot;ec-wrapper&quot;]/div[@class=&quot;ec-store ec-store__checkout-page&quot;]/div[@class=&quot;ec-store__content-wrapper&quot;]/div[@class=&quot;ec-cart notranslate&quot;]/div[@class=&quot;ec-cart__body&quot;]/div[@class=&quot;ec-cart__body-inner&quot;]/div[@class=&quot;ec-cart__steps&quot;]/div[@class=&quot;ec-cart__step ec-cart-step ec-cart-step--payment ec-cart-step--current&quot;]/div[@class=&quot;ec-cart-step__wrap&quot;]/div[@class=&quot;ec-cart-step__body&quot;]/div[@class=&quot;ec-form&quot;]/div[@class=&quot;ec-form__row ec-form__row--continue&quot;]/div[@class=&quot;ec-form__cell ec-form__cell--6&quot;]/div[@class=&quot;form-control form-control--button form-control--large form-control--primary form-control--flexible form-control--done&quot;]/button[@class=&quot;form-control__button&quot;]/div[@class=&quot;form-control__loader&quot;]</value>
      <webElementGuid>13fed75e-05f1-4fcc-b5cb-985b0bbe419d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ecwid-products']/div[2]/div/div/div[2]/div/div[2]/div/div/div[2]/div/div[2]/div[4]/div[2]/div[2]/div[6]/div/div/div/button/div</value>
      <webElementGuid>e8b277f2-56b2-43d0-92f6-29aa1cf56e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>a9144cf9-7b50-48c3-b30f-8df7b25021c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
