<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>51aadbf4-2bad-484f-9a73-a82a8c475872</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='category-36641004']/div/a/div/div/div/div/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Flash Sale&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Flash Sale&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>84aacb06-ddcd-43f5-9f3a-de8b36272181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d2j6dbq0eux0bg.cloudfront.net/images/7193083/4014191301.png</value>
      <webElementGuid>cae439cb-d6ea-4b18-9238-2cef0f509b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Flash Sale</value>
      <webElementGuid>1ab22182-f8ef-487b-af7e-4af3d7e67ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>low</value>
      <webElementGuid>cf80a07f-890f-43f8-a5f4-488530152768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category-36641004&quot;)/div[@class=&quot;ins-component__item-wrap&quot;]/a[@class=&quot;ins-component__item-wrap-inner&quot;]/div[@class=&quot;ins-component__card&quot;]/div[@class=&quot;ins-component__image&quot;]/div[@class=&quot;ins-component__bg&quot;]/div[@class=&quot;ins-component__bg-image&quot;]/picture[@class=&quot;ins-picture ins-picture--full&quot;]/img[1]</value>
      <webElementGuid>86f9557c-7c67-4026-be36-885f875ccb10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='category-36641004']/div/a/div/div/div/div/picture/img</value>
      <webElementGuid>6419e4a5-d0d5-4215-9bea-9a69c0a31e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Flash Sale']</value>
      <webElementGuid>70c63fc2-766d-467e-b643-5799854a4131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/picture/img</value>
      <webElementGuid>a663d955-1b81-4ba7-a789-e5609dd7800d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d2j6dbq0eux0bg.cloudfront.net/images/7193083/4014191301.png' and @alt = 'Flash Sale']</value>
      <webElementGuid>23e6b0a1-7687-4260-8afe-4bb3316d41be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
