<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Please choose_form-control__loader</name>
   <tag></tag>
   <elementGuidId>d80aacd8-a4c0-43b7-ac7c-6ecc77a3e303</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ecwid-products']/div[2]/div/div/div[2]/div/div[2]/div/div/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[2]/div/div/div/div/button/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-control__loader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>495c747f-0d8c-4780-a40c-491ecf73ae5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__loader</value>
      <webElementGuid>b37711e9-847a-406c-bc29-8cf30d9f023c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ecwid-products&quot;)/div[@class=&quot;ec-storefront-v2 ec-size ec-size--xxs ec-size--xs ec-size--s ec-size--m ecwid-no-touch ecwid-supports-cssanimations ecwid-responsive ecwid-no-dragndrop&quot;]/div[1]/div[@class=&quot;ecwid-productBrowser ecwid-productBrowser-ElmCheckoutShippingAddressPage&quot;]/div[2]/div[@class=&quot;ec-wrapper&quot;]/div[@class=&quot;ec-store ec-store__checkout-page&quot;]/div[@class=&quot;ec-store__content-wrapper&quot;]/div[@class=&quot;ec-cart notranslate&quot;]/div[@class=&quot;ec-cart__body&quot;]/div[@class=&quot;ec-cart__body-inner&quot;]/div[@class=&quot;ec-cart__steps&quot;]/div[@class=&quot;ec-cart__step ec-cart-step ec-cart-step--address ec-cart-step--current&quot;]/div[@class=&quot;ec-cart-step__wrap&quot;]/div[@class=&quot;ec-cart-step__body&quot;]/div[@class=&quot;ec-cart-step__section&quot;]/div[@class=&quot;ec-cart-step__section&quot;]/div[@class=&quot;ec-form&quot;]/div[@class=&quot;ec-form__row ec-form__row--continue&quot;]/div[@class=&quot;ec-form__cell ec-form__cell--6&quot;]/div[@class=&quot;form-control form-control--button form-control--large form-control--primary form-control--flexible form-control--done&quot;]/button[@class=&quot;form-control__button&quot;]/div[@class=&quot;form-control__loader&quot;]</value>
      <webElementGuid>d118bcbf-15e6-47cc-af76-c5bbfcb69d71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ecwid-products']/div[2]/div/div/div[2]/div/div[2]/div/div/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[2]/div/div/div/div/button/div</value>
      <webElementGuid>52da69d7-9ec2-456f-8e72-2c55659e21ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>14a0745f-dcbb-497b-a97b-b809c495a59a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
