<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street address, apartment, suite, flo_b7b2f3</name>
   <tag></tag>
   <elementGuidId>316d3166-9b4e-4046-9598-aad2da436d6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ec-city-list']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ec-city-list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;City&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>baa5a8a4-8764-496a-b7f2-99b4a83162ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ec-city-list</value>
      <webElementGuid>a0d010e0-befc-40b8-909b-65ef19e5c70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__text</value>
      <webElementGuid>1456361a-6c0a-4e5f-bd4b-e284e130a7db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>7868d756-9021-4a38-9aa0-d26d1489618a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>6e12e9f4-750b-48e8-b21e-6a0effd41ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>shipping address-level2</value>
      <webElementGuid>705e22d6-ad04-4ff4-9822-2682f8528989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f85ea241-8fdf-4d43-88c2-7884317125eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enterkeyhint</name>
      <type>Main</type>
      <value>next</value>
      <webElementGuid>2172c433-61b8-42f5-9a9e-6e6e0efe6e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>153dc3d2-d827-42f6-8466-2f9a2bc1be03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>9b9df5f0-7e94-440b-99a9-87d61fb7ba81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ec-city-list&quot;)</value>
      <webElementGuid>dfa32c9d-a39a-4f40-a3bd-390e1e19e2d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ec-city-list']</value>
      <webElementGuid>6d09e834-63b1-426a-8569-b62751a70778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ecwid-products']/div[2]/div/div/div[2]/div/div[2]/div/div/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[2]/form/div[5]/div/div/input</value>
      <webElementGuid>0cf5f8e7-ce18-4001-a2da-6d09db870e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>4045ee86-99f3-4f2c-894a-9eeda00223c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ec-city-list' and @type = 'text' and @name = 'city']</value>
      <webElementGuid>2d06f9f2-e38e-42a4-a70f-e8a3fa9bcb13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
