<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Menu</name>
   <tag></tag>
   <elementGuidId>3ec6a759-ae84-4361-850a-67c07aa6c0aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='tile-header-2Mph3d']/div[2]/div/div/div/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ins-header__icon.ins-header__icon--burger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;!ADA.Menu!&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f2f90fd-c212-43a8-9575-db7a0f34002f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ins-header__icon ins-header__icon--burger</value>
      <webElementGuid>a1a82e56-cbe1-4b0b-b06b-31cfe1296363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#menu</value>
      <webElementGuid>40aeed19-4185-4199-a7e4-28b4e95d4926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b4a76bd8-3c2c-4716-981c-9cf920476c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>!ADA.Menu!</value>
      <webElementGuid>931ccab1-ea72-4765-83bb-956cd971d02b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>5c4dfb0e-1295-4d8a-9e0d-7802b2751d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tile-header-2Mph3d&quot;)/div[@class=&quot;ins-tile__wrap ins-tile__animated&quot;]/div[@class=&quot;ins-header&quot;]/div[@class=&quot;ins-header__wrap&quot;]/div[@class=&quot;ins-header__inner&quot;]/div[@class=&quot;ins-header__row&quot;]/div[@class=&quot;ins-header__left&quot;]/a[@class=&quot;ins-header__icon ins-header__icon--burger&quot;]</value>
      <webElementGuid>eb2bc999-1d04-460c-90a5-0790f2549b70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='tile-header-2Mph3d']/div[2]/div/div/div/div/div[2]/a</value>
      <webElementGuid>b66a55d0-1248-46e2-b7ce-1956c9315883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore the Latest Arrivals!'])[1]/following::a[2]</value>
      <webElementGuid>a29b5599-55cf-4981-9bfe-fa2e99390e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENJOY FREE DELIVERY ON ORDERS OVER 20 - RIALS IN MUSCAT'])[1]/following::a[3]</value>
      <webElementGuid>d79ed6cd-4c66-49db-8069-3c7d30a0beb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit our FB'])[1]/preceding::a[4]</value>
      <webElementGuid>8a9353d3-1b19-448d-b079-93a4f13b9681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#menu')]</value>
      <webElementGuid>7a6b5145-dec9-47c9-a10f-1623ed4c361b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/a</value>
      <webElementGuid>f4413a19-9812-4ea8-ba2c-8689b7d64e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#menu' and (text() = 'Menu' or . = 'Menu')]</value>
      <webElementGuid>89e90312-5b7d-4700-b40a-794ef1f71e14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
