<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Payment Options</name>
   <tag></tag>
   <elementGuidId>aca62a9f-18db-486a-80c1-fc4fe9475b22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='tile-header-2Mph3d']/div[2]/div/div/div[2]/div/div/nav/div[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Payment Options&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>64a17431-a231-484f-8c39-a6ee5bd9bfc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ins-header__sidebar-menu-link-title</value>
      <webElementGuid>eda09258-3b13-4dcf-835d-b233b06fc6d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/paymentoptions</value>
      <webElementGuid>48e31a52-6fe3-43a4-80af-1244b7b9ebac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>6699df17-68b4-4d3c-a149-5eba0b97aa3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payment Options</value>
      <webElementGuid>dec5d83c-147d-411d-aa1b-2be34e932873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tile-header-2Mph3d&quot;)/div[@class=&quot;ins-tile__wrap ins-tile__animated&quot;]/div[@class=&quot;ins-header&quot;]/div[@class=&quot;ins-header__wrap&quot;]/div[@class=&quot;ins-header__sidebar ins-header__sidebar--menu&quot;]/div[@class=&quot;ins-header__sidebar-menu&quot;]/div[@class=&quot;ins-header__sidebar-menu-wrap&quot;]/nav[@class=&quot;ins-header__sidebar-menu-inner&quot;]/div[@class=&quot;ins-header__sidebar-menu-link&quot;]/a[@class=&quot;ins-header__sidebar-menu-link-title&quot;]</value>
      <webElementGuid>108b223c-3dda-48c0-960c-89584120da7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='tile-header-2Mph3d']/div[2]/div/div/div[2]/div/div/nav/div[7]/a</value>
      <webElementGuid>953d3d03-c858-43d0-97b3-87d40f058855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Payment Options')])[2]</value>
      <webElementGuid>cb6d0327-30f8-4c27-b583-d4d1edf2b21d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Fee'])[2]/following::a[1]</value>
      <webElementGuid>b4a3eb8c-2dc5-496a-99a1-fe39b6a6ee07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our App'])[2]/following::a[2]</value>
      <webElementGuid>09e4b451-3bf9-47c4-9d3c-5e30fc5ec9d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit our FB'])[2]/preceding::a[4]</value>
      <webElementGuid>605577d9-9dcd-482a-b183-7d0f8c3c0130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Happy Shopping 🧡'])[1]/preceding::a[5]</value>
      <webElementGuid>5fc771ad-89f2-4bf6-852f-6869015a548f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/paymentoptions')])[2]</value>
      <webElementGuid>8dca6e2c-5015-4fa5-9e01-fb42296872b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/nav/div[7]/a</value>
      <webElementGuid>3517134f-1253-46c2-8621-416f7522e232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/paymentoptions' and (text() = 'Payment Options' or . = 'Payment Options')]</value>
      <webElementGuid>c06d1adc-8b08-44d9-a2d7-bd067bd55c8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
