<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Gcash</name>
   <tag></tag>
   <elementGuidId>29842d4c-a23b-4f58-855e-d98f8d856fbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='feature-list-Rugwmz-FLT23']/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#feature-list-Rugwmz-FLT23 > div.ins-tile__item-header > div.ins-tile__item-title > div.ins-tile__feature-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Gcash&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dfd94009-454b-4000-a13f-3e6ff9519055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ins-tile__feature-title</value>
      <webElementGuid>f832e628-8b42-479d-9f42-d845a39bad3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gcash</value>
      <webElementGuid>12e3c5ba-5c47-4dfa-ae2c-859834b8577e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;feature-list-Rugwmz-FLT23&quot;)/div[@class=&quot;ins-tile__item-header&quot;]/div[@class=&quot;ins-tile__item-title&quot;]/div[@class=&quot;ins-tile__feature-title&quot;]</value>
      <webElementGuid>ba7b92c9-6cbe-4ea8-b3a0-cef768cf17e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='feature-list-Rugwmz-FLT23']/div/div/div[2]</value>
      <webElementGuid>842c4333-bfb4-46c7-896b-24373c4b9a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Transfer'])[1]/following::div[10]</value>
      <webElementGuid>3b2f0738-fa35-409c-91de-b41bf7f5e2d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Payment'])[1]/preceding::div[7]</value>
      <webElementGuid>27ae16bc-a9d9-4f7c-9ea2-8b2cbadfb541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gcash']/parent::*</value>
      <webElementGuid>3d981b1a-cad0-4e99-b473-fd8af607d4c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]</value>
      <webElementGuid>64adf191-88c6-40e3-a8f4-15ac6ce98868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Gcash' or . = 'Gcash')]</value>
      <webElementGuid>7ed6d94a-ca8a-40a5-b120-eb5d0ce9fa46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
