<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Location</name>
   <tag></tag>
   <elementGuidId>604364b9-b0b0-4fe9-b9e6-e95755a784db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='tile-header-2Mph3d']/div[2]/div/div/div[2]/div/div/nav/div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Location&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b25ab99b-e419-4376-ade1-9651d4a7c021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ins-header__sidebar-menu-link-title</value>
      <webElementGuid>36ceb84c-6edd-4115-9a4f-d0be33a24a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/location</value>
      <webElementGuid>e05a8bf0-b4a7-4ee6-a0da-e1c05fa64c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>712dae66-49c5-4351-a813-5b25e7498cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Location</value>
      <webElementGuid>d8abeb1b-cd9a-4059-bf48-1ca0b9d219c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tile-header-2Mph3d&quot;)/div[@class=&quot;ins-tile__wrap ins-tile__animated&quot;]/div[@class=&quot;ins-header&quot;]/div[@class=&quot;ins-header__wrap&quot;]/div[@class=&quot;ins-header__sidebar ins-header__sidebar--menu&quot;]/div[@class=&quot;ins-header__sidebar-menu&quot;]/div[@class=&quot;ins-header__sidebar-menu-wrap&quot;]/nav[@class=&quot;ins-header__sidebar-menu-inner&quot;]/div[@class=&quot;ins-header__sidebar-menu-link&quot;]/a[@class=&quot;ins-header__sidebar-menu-link-title&quot;]</value>
      <webElementGuid>66f63b40-8544-4fa4-8b24-772354ec588f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='tile-header-2Mph3d']/div[2]/div/div/div[2]/div/div/nav/div[4]/a</value>
      <webElementGuid>2f251365-0c5b-4072-bc13-d9e30ce5ec8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Location')])[2]</value>
      <webElementGuid>61067152-8456-4955-90d6-77e6bed685bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact us'])[2]/following::a[1]</value>
      <webElementGuid>767d9eed-53f5-494a-8b60-dd3f274dc445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For Children'])[1]/following::a[2]</value>
      <webElementGuid>a6cd3afc-4f96-4780-afae-257c7126a47a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our App'])[2]/preceding::a[1]</value>
      <webElementGuid>2c2a066b-a761-4904-b5ee-7ca76315ac11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Fee'])[2]/preceding::a[2]</value>
      <webElementGuid>95bae895-66fe-4a18-b6bd-19f4c0989d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/location')])[2]</value>
      <webElementGuid>12fb4092-dfbc-4467-a48a-2b35855bacc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/nav/div[4]/a</value>
      <webElementGuid>dd29fac2-a913-4571-9143-6889eac52041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/location' and (text() = 'Location' or . = 'Location')]</value>
      <webElementGuid>0892fe81-a886-4c3b-a008-7247e15a983f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
