<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Whatsap Us_ins-tile__map-frame</name>
   <tag></tag>
   <elementGuidId>ba31d53c-2701-4243-b482-b306fe8cb655</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='tile-location-pgMbbJ']/div[2]/div[3]/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.ins-tile__map-frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Location on Google Maps&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>45813f35-c94c-4eee-8f72-57bbea346612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ins-tile__map-frame</value>
      <webElementGuid>84c55708-a5e7-40f8-ac70-7579aa6dfabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/maps/embed/v1/place?key=AIzaSyCNCmAGyN4bJYu5qeLgbASzZafm-M5TA_o&amp;language=en&amp;zoom=16&amp;maptype=roadmap&amp;q=HGRH+JHG%2C+Village%2C+Muscat%2C+Oman</value>
      <webElementGuid>db1cc7b8-23f7-44fc-8170-59f2e118b6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>86665e5e-d59e-4997-a186-280bdd5f6265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Location on Google Maps</value>
      <webElementGuid>25112fd2-5132-4bef-bb97-f4bd5146fa23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tile-location-pgMbbJ&quot;)/div[@class=&quot;ins-tile__wrap ins-tile__animated&quot;]/div[@class=&quot;ins-tile__map ins-tile__animated&quot;]/div[@class=&quot;ins-tile__map-frame-wrapper&quot;]/iframe[@class=&quot;ins-tile__map-frame&quot;]</value>
      <webElementGuid>5a9805ed-ba7b-41e8-ad6a-6c030adca514</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='tile-location-pgMbbJ']/div[2]/div[3]/div/iframe</value>
      <webElementGuid>6ecd4a47-b6fe-4d01-80e0-3ec15ad16228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>95cb46b6-45f2-4595-8f23-fb5fb4abdbbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://www.google.com/maps/embed/v1/place?key=AIzaSyCNCmAGyN4bJYu5qeLgbASzZafm-M5TA_o&amp;language=en&amp;zoom=16&amp;maptype=roadmap&amp;q=HGRH+JHG%2C+Village%2C+Muscat%2C+Oman' and @title = 'Location on Google Maps']</value>
      <webElementGuid>e2b46624-c198-4528-9b4d-f2abf1df02be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
