<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Free_form-control__loader</name>
   <tag></tag>
   <elementGuidId>3f038932-88eb-4628-b68e-baa2a3e0527c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ecwid-products']/div[2]/div/div/div[2]/div/div[2]/div/div/div[2]/div/div[2]/div[3]/div[2]/div[2]/div[2]/div/div/div/div/button/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-control__loader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07f940ed-11df-429f-a0ac-166a9de5c6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__loader</value>
      <webElementGuid>d66f108f-37cc-413f-89ca-3d41c7a44b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ecwid-products&quot;)/div[@class=&quot;ec-storefront-v2 ec-size ec-size--xxs ec-size--xs ec-size--s ec-size--m ecwid-no-touch ecwid-supports-cssanimations ecwid-responsive ecwid-no-dragndrop&quot;]/div[1]/div[@class=&quot;ecwid-productBrowser ecwid-productBrowser-ElmCheckoutDeliveryPage&quot;]/div[2]/div[@class=&quot;ec-wrapper&quot;]/div[@class=&quot;ec-store ec-store__checkout-page&quot;]/div[@class=&quot;ec-store__content-wrapper&quot;]/div[@class=&quot;ec-cart notranslate&quot;]/div[@class=&quot;ec-cart__body&quot;]/div[@class=&quot;ec-cart__body-inner&quot;]/div[@class=&quot;ec-cart__steps&quot;]/div[@class=&quot;ec-cart__step ec-cart-step ec-cart-step--delivery ec-cart-step--current&quot;]/div[@class=&quot;ec-cart-step__wrap&quot;]/div[@class=&quot;ec-cart-step__body&quot;]/div[@class=&quot;ec-cart-step__section&quot;]/div[@class=&quot;ec-form&quot;]/div[@class=&quot;ec-form__row&quot;]/div[@class=&quot;ec-form__cell ec-form__cell--6&quot;]/div[@class=&quot;form-control form-control--button form-control--large form-control--primary form-control--flexible form-control--done&quot;]/button[@class=&quot;form-control__button&quot;]/div[@class=&quot;form-control__loader&quot;]</value>
      <webElementGuid>0cfca1ce-d0eb-4437-805e-2608fbefef84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ecwid-products']/div[2]/div/div/div[2]/div/div[2]/div/div/div[2]/div/div[2]/div[3]/div[2]/div[2]/div[2]/div/div/div/div/button/div</value>
      <webElementGuid>833d9b1f-ef14-4219-9c66-9ff79d271230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>0dc16ff5-d2f8-40bf-ba9e-09508922796c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
