<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to Bag</name>
   <tag></tag>
   <elementGuidId>46635556-a584-4784-9513-94a93c27bb6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-control.form-control--button.form-control--large.form-control--primary.form-control--flexible.form-control--animated.details-product-purchase__add-to-bag.form-control__button--icon-center.form-control--done > button.form-control__button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add to Bag&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>36350bfe-1f48-451a-9205-ad333f15be92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control__button</value>
      <webElementGuid>72e75d45-1a6b-43a3-800b-5562d166aee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b12dc681-8576-4dcc-a542-bb7d12824d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to Bag</value>
      <webElementGuid>3fbaae74-0e14-4855-92cf-05fe26afeb10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ecwid-products&quot;)/div[@class=&quot;ec-storefront-v2 ec-size ec-size--xxs ec-size--xs ec-size--s ec-size--m ecwid-no-touch ecwid-supports-cssanimations ecwid-responsive ecwid-no-dragndrop&quot;]/div[1]/div[@class=&quot;ecwid-productBrowser ecwid-productBrowser-ProductPage ecwid-productBrowser-ProductPage-254957040&quot;]/div[1]/div[1]/div[2]/div[@class=&quot;ec-wrapper&quot;]/div[@class=&quot;ec-store ec-store__product-page ec-store__product-page--254957040 ec-store__product-page--c28520150 ec-store__product-page--c36641004&quot;]/div[@class=&quot;ec-store__content-wrapper&quot;]/div[1]/div[@class=&quot;product-details product-details--layout-sidebar-right product-details--description-basic&quot;]/div[@class=&quot;product-details__sidebar&quot;]/div[@class=&quot;product-details-module product-details__action-panel details-product-purchase&quot;]/div[@class=&quot;product-details-module__content product-details-module__content--indented&quot;]/div[@class=&quot;details-product-purchase__controls&quot;]/div[@class=&quot;details-product-purchase__bag-controls&quot;]/div[@class=&quot;details-product-purchase__add-buttons&quot;]/div[@class=&quot;form-control form-control--button form-control--large form-control--primary form-control--flexible form-control--animated details-product-purchase__add-to-bag form-control__button--icon-center form-control--done&quot;]/button[@class=&quot;form-control__button&quot;]</value>
      <webElementGuid>ce7a061e-6e20-409b-95ea-bdf8db08381d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>72c09d17-c32b-4734-915a-40f610638504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ecwid-products']/div[2]/div/div/div/div/div[2]/div/div/div/div/div[2]/div[2]/div[4]/div/div[2]/div/div/div[2]/button</value>
      <webElementGuid>e924f70b-9651-4aae-8826-d595c1ad5b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add More'])[1]/following::button[1]</value>
      <webElementGuid>0b728b7c-843b-4624-ba77-9a8f9283aeaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity:'])[1]/following::button[2]</value>
      <webElementGuid>6d3ffdbd-1be7-49d4-b1f4-11a39bc58a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to Checkout'])[1]/preceding::button[1]</value>
      <webElementGuid>c83a5ff0-634e-4698-80f8-c6db585c4ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>2778cb6b-bddc-47ed-ae34-a21d7d654984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Add to Bag' or . = 'Add to Bag')]</value>
      <webElementGuid>b9e79b9c-1d2d-4439-b9a9-3111b197fb04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
